apiVersion: apps/v1
kind: Deployment
metadata:
  name: tesflix-deployment
  labels:
    app: tesflix
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tesflix
  template:
    metadata:
      labels:
        app: tesflix
    spec:
      containers:
      - name: tesflix
        image: naveennallamsetti/tesflix-hub:latest
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: tesflix-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: tesflix-secrets
              key: DATABASE_URL
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: tesflix-secrets
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: tesflix-secrets
              key: AWS_SECRET_ACCESS_KEY
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 500m
            memory: 2Gi
